{% set name = "clickhouse-driver" %}
{% set version = "0.1.3" %}
{% set sha256 = "1a9a0815bddc0082d2155c1803c4ae79b1fbe28ae276fe9703650208acbc5ec3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - cython
    - python

  run:
    - python
    - six
    - pytz
    - tzlocal
    - ipaddress  # [py27]
    - enum34  # [py27]

test:
  imports:
    - clickhouse_driver
    - clickhouse_driver.columns
    - clickhouse_driver.compression
    - clickhouse_driver.settings
    - clickhouse_driver.streams
    - clickhouse_driver.util
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mymarilyn/clickhouse-driver
  license: MIT
  summary: 'Python driver with native interface for ClickHouse'
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
    - xzkostyan
    - cpcloud
    - xmnlab
    - xhochy
