{% set name = "clickhouse-driver" %}
{% set version = "0.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1bec70343bde9e9a55c2254c5960d34c682ff7d60256589226d96c67a112f95a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - cython
    - python
    - setuptools
  run:
    - python
    - six
    - pytz
    - tzlocal

test:
  imports:
    - clickhouse_driver
    - clickhouse_driver.columns
    - clickhouse_driver.compression
    - clickhouse_driver.settings
    - clickhouse_driver.streams
    - clickhouse_driver.util
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mymarilyn/clickhouse-driver
  license: MIT
  summary: Python driver with native interface for ClickHouse
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
    - xzkostyan
    - cpcloud
    - xmnlab
    - xhochy
